### ISSUE TITLE
addAppToAppDataUsageList fails on some running apps that don't have PackageMaager label

### ISSUE THREAD

**Issue by RoundSparrow** [octohub/NetLive#3]
Obviously depends what apps you have on your device - but I see in some testing that at least one app out there doesn't have a Label on it - so addAppToAppDataUsageList fails to add it to a list.  Maybe come up with a scheme for an alternate name (process ID?) do use when it fails?

One of the apps I saw on Android 4.4 system: com.android.keyguard

**Comment by octohub** [comment]
@RoundSparrow Perhaps a fix for this would be to show a stripped down version of the package name? So in the case of `com.android.keyguard`, maybe just call it `keyguard`? Parsing package names might be tricky though. Alternatively we could just fall back to showing the package name.

What are your thoughts?

**Comment by RoundSparrow** [comment]
I just completed some more testing - and maybe this problem is an illusion.  It seems Android internally in 4.4 catches the exception and isn't making it back to the app.  It in fact did use the "com.android.keyboard" as the label name - despite Logcat showing a warning exception.  In this system with 60 apps or so, it was the only one to show the exception like this.

I can close the issue here, as it may be a Framework version-specific issue and seems benign.
